apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-pdf-external-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pdf.bbg.pe
      secretName: pdf-bbg-pe-tls
  rules:
    - host: pdf.bbg.pe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stirling-pdf-external-svc
                port:
                  number: 80