apiVersion: v1
data:
  frpc.toml: |
    serverAddr = "161.132.4.98"
    serverPort = 7000

    [auth]
    token = "da2cee8f9759dda3a294ca963743922d4dc6400fcf316d0499215729efc74533"

    [[proxies]]
    name = "nginx-ingress-http"
    type = "tcp"
    localIP = "192.168.100.240"
    localPort = 80
    remotePort = 80

    [[proxies]]
    name = "nginx-ingress-https"
    type = "tcp"
    localIP = "192.168.100.240"
    localPort = 443
    remotePort = 443

    [[proxies]]
    name = "k8s-api"
    type = "tcp"
    localIP = "192.168.100.230"
    localPort = 6443
    remotePort = 6443

    [[proxies]]
    name = "oracle-23ai"
    type = tcp
    localIP = "192.168.100.191"
    localPort = 1521
    remotePort = 1521
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"frpc.toml":"serverAddr = \"161.132.4.98\"\nserverPort = 7000\n\n[auth]\ntoken = \"da2cee8f9759dda3a294ca963743922d4dc6400fcf316d0499215729efc74533\"\n\n[[proxies]]\nname = \"nginx-ingress-http\"\ntype = \"tcp\"\nlocalIP = \"192.168.100.240\"\nlocalPort = 80\nremotePort = 80\n\n[[proxies]]\nname = \"nginx-ingress-https\"\ntype = \"tcp\"\nlocalIP = \"192.168.100.240\"\nlocalPort = 443\nremotePort = 443\n\n[[proxies]]\nname = \"k8s-api\"\ntype = \"tcp\"\nlocalIP = \"192.168.100.230\"\nlocalPort = 6443\nremotePort = 6443\n\n[[proxies]]\nname = \"oracle-23ai\"\ntype = tcp\nlocalIP = \"192.168.100.191\"\nlocalPort = 1521\nremotePort = 1521\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"frpc-config-bbg","namespace":"ingress-nginx"}}
  creationTimestamp: "2025-10-26T02:39:18Z"
  name: frpc-config-bbg
  namespace: ingress-nginx
  resourceVersion: "31353553"
  uid: d5193e55-c863-45a9-9e80-b9c5a5daf908
