apiVersion: v1
kind: Service
metadata:
  name: nextcloud-external-svc
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
  # Al no definir un 'selector', Kubernetes no buscará pods, sino que buscará un objeto 'Endpoints' con el mismo nombre.

---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud-external-svc # DEBE coincidir exactamente con el nombre del Service
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.100.161 # La IP de tu servidor Docker
    ports:
      - port: 8002 # El puerto donde escucha Nextcloud
        name: http
