apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-external-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nas.bbg.pe
      secretName: nas-bbg-pe-tls
  rules:
    - host: nas.bbg.pe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-external-svc
                port:
                  number: 80