apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
  namespace: ingress-nginx
data:
  frpc.toml: |
    serverAddr = "VPS"
    serverPort = 7000

    [auth]
    token = "TOKEN"

    [[proxies]]
    name = "nginx-ingress-http"
    type = "tcp"
    localIP = "192.168.100.240"
    localPort = 80
    remotePort = 80

    [[proxies]]
    name = "nginx-ingress-https"
    type = "tcp"
    localIP = "192.168.100.240"
    localPort = 443
    remotePort = 443

    [[proxies]]
    name = "k8s-api"
    type = "tcp"
    localIP = "192.168.100.230"
    localPort = 6443
    remotePort = 6443