bindPort = 7000
allowPorts = [
  { start = 22, end = 22 },
  { start = 80, end = 80 },
  { start = 443, end = 443 },
  { start = 6443, end = 6443 },
  { start = 7500, end = 7500 },
  { start = 8080, end = 8080 }
]
# vhostHTTPPort = 80
# vhostHTTPSPort = 443

webServer.port = 7500
webServer.user = "USERNAME"
webServer.password = "PASSWORD"
webServer.addr = "0.0.0.0"

[auth]
token = "TOKEN"