apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-bbg-pe-tls
  namespace: harbor
spec:
  secretName: harbor-bbg-ingress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: harbor.bbg.pe
  dnsNames:
  - harbor.bbg.pe