services:
  brave:
    image: lscr.io/linuxserver/brave:latest
    container_name: brave-browser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - CUSTOM_USER=luis122448
      - PASSWORD=${PASSWORD}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - brave_config:/config
    ports:
      - 8005:3001
    shm_size: "2gb"
    restart: always

volumes:
  brave_config: