apiVersion: v1
kind: Service
metadata:
  name: webtop-external-svc
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4500
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: webtop-external-svc-slice
  namespace: default
  labels:
    kubernetes.io/service-name: webtop-external-svc
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 4500
endpoints:
  - addresses:
      - "192.168.100.142"