apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webtop-external-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "webtop-external-svc"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # Desactivamos cualquier l√≠mite de buffers que pueda cortar los scripts
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      # Evitar que Nginx guarde nada en cache
      proxy_cache_bypass $http_upgrade;
      proxy_no_cache $http_upgrade;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - webtop.bbg.pe
      secretName: webtop-bbg-pe-tls
  rules:
    - host: webtop.bbg.pe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webtop-external-svc
                port:
                  number: 80
