apiVersion: v1
kind: Service
metadata:
  name: brave-browser-external-svc
  namespace: default
spec:
  ports:  
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8005
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: brave-browser-external-svc-slice
  namespace: default
  labels:
    kubernetes.io/service-name: brave-browser-external-svc
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8005
endpoints:
  - addresses:
      - "192.168.100.162"
