apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brave-browser-external-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "brave-browser-external-svc"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - brave.local.bbg.pe
    secretName: brave-browser-external-tls
  rules:
  - host: brave.local.bbg.pe
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brave-browser-external-svc
            port:
              number: 80
