apiVersion: v1
kind: Service
metadata:
  name: navidrome-external-svc
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8003

---
apiVersion: v1
kind: Endpoints
metadata:
  name: navidrome-external-svc # Must match Service name exactly
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.100.161
    ports:
      - port: 8003
        name: http